# Generated by Django 4.2.5 on 2023-09-26 16:21

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.utils.RandomFileName('profile_pics')),
        ),
    ]
