# Generated by Django 4.2.5 on 2023-09-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pin_image'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('pin', 'user'), name='unique_like'),
        ),
    ]
