# Generated by Django 4.2.5 on 2023-10-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_like_unique_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-created_at']},
        ),
    ]
